#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Command\Command;
use Goutte\Client;
use \DomainFinder\DomainFinder;

$console = new Application('SEO Tools', '1.0');

$console
    ->register('find:interactive')
    ->setDefinition(array(
    	new InputOption( 'log', null, InputOption::VALUE_NONE, 'Whether or not you want to log the results so you can use them later', null),
    	new InputOption( 'max_page_to_look', null, InputOption::VALUE_REQUIRED, 'To avoid being blocked by google, this tool will stop when reaching this page number', 10),
        new InputArgument( 'query', InputArgument::REQUIRED, 'Keywords to search in Google. If you need more than one keyword, you can use quotes like "buy kindle"'),
        new InputArgument( 'domains', InputArgument::IS_ARRAY | InputArgument::REQUIRED, 'Domains, separated by spaces, to find in the search results. Better without the www'),
    ))
    ->setDescription('Find the position of your domain in google search results')
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($console){
    	$time 		= microtime(true);
        $pdo        = new \PDO('sqlite:/var/www/google/log.db');
    	$domains 	= $input->getArgument('domains');

    	//$event_dispatcher 	= new \DomainFinder\Event\EventDispatcher();
        $event_dispatcher   = \Symfony\Component\EventDispatcher\EventDispatcher();
		//$event_dispatcher->addSubscriber( new \DomainFinder\Event\OutputListener( $output ) );
		if ( $input->getOption('log') ){
			$event_dispatcher->addSubscriber( new \DomainFinder\Event\DatabaseListener() );
		}

        $domain_finder = new DomainFinder( $event_dispatcher );

    	foreach ( $domains as $domain ){
    		$table 	= new \Symfony\Component\Console\Helper\TableHelper();
			$table->setHeaders( array( '#', 'Url', 'Is Yours?' ) );

			
			$domain_finder->find( $domain, $input->getArgument('query'), $input->getOption('max_page_to_look') );

			$counter = 0;
			foreach ( $domain_finder->getGoogleResults() as $result ) {
				$table->addRow( array( ++$counter, $result->getHost(), ( $result->is($domain)?'[X]':'[]' ) ) );
			}

			$table->render( $output );
    	}
		
		$output->writeln( "<info>Elapsed time: " . round( microtime(true) - $time, 3 ) . "</info>");
    })
;

$console
    ->register('find:daemon')
    ->setDefinition(array(
        new InputOption( 'max_page_to_look', null, InputOption::VALUE_REQUIRED, 'To avoid being blocked by google, this tool will stop when reaching this page number', 10),
    ))
    ->setDescription( 'Take the queries saved in the backend and try to find the selected domains for those google queries. It saves the results so you can see the results in the backend.' )
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($console){
        $time       = microtime(true);
        $pdo        = new \PDO('sqlite:/var/www/google/log.db');
        $sql       = <<<QUERY
SELECT
    query, domain
FROM
    `queries`
QUERY;
        $statement  = $pdo->prepare( $sql );
        $statement->execute();
        $queries    = $statement->fetchAll( \PDO::FETCH_ASSOC );

        $event_dispatcher   = new \Symfony\Component\EventDispatcher\EventDispatcher();
        $event_dispatcher->addSubscriber( new \DomainFinder\Event\DatabaseListener( $pdo ) );
        //$event_dispatcher->addSubscriber( new \DomainFinder\Event\OutputListener( $output ) );
        //$event_dispatcher->addSubscriber( new \DomainFinder\Event\LoggerListener( $pdo ) );

        foreach ( $queries as $query ){
            $domains = explode( ' ', $query['domain'] );
            foreach ( $domains as $domain ){
                $domain_finder = new DomainFinder( $event_dispatcher );
                $domain_finder->find( $domain, $query['query'], $input->getOption('max_page_to_look') );
            }
        }
        
        $output->writeln( "<info>Elapsed time: " . round( microtime(true) - $time, 3 ) . "</info>");
    })
;

$console->run();