#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Command\Command;
use Goutte\Client;
use \DomainFinder\DomainFinder;

$console = new Application('SEO Tools', '1.0');

$console
    ->register('find')
    ->setDefinition(array(
        new InputArgument( 'domain', InputArgument::REQUIRED, 'Domain to find in the search results. Better without the www'),
        new InputArgument( 'query', InputArgument::REQUIRED, 'Keywords to search in Google. If you need more than one keyword, you can use quotes like "buy kindle"'),
        new InputArgument( 'max_page_to_look', InputArgument::OPTIONAL, 'To avoid being blocked by google, this tool will stop when reaching this page number', 10),
    ))
    ->setDescription('Find the position of your domain in google search results')
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($console){
    	$time 	= microtime(true);
    	$domain = $input->getArgument('domain');

		$table 	= $console->getHelperSet()->get( 'table' );
		$table->setHeaders( array( '#', 'Url', 'Is Yours?' ) );

		$event_dispatcher 	= new \DomainFinder\Event\EventDispatcher();
		$event_dispatcher->addSubscriber( new \DomainFinder\Event\OutputListener( $output ) );
		$domain_finder 		= new DomainFinder( $domain, $input->getArgument('max_page_to_look'), $event_dispatcher );
		$domain_finder->find( $input->getArgument('query') );

		$counter = 0;
		foreach ( $domain_finder->getGoogleResults() as $result ) {
			$table->addRow( array( ++$counter, $result->getHost(), ( $result->is($domain)?'[X]':'[]' ) ) );
		}

		$table->render( $output );
		$output->writeln( "<info>Elapsed time: " . round( microtime(true) - $time, 3 ) . "</info>");
    })
;
$console->run();