#!/usr/bin/env php
<?php

error_reporting( E_ALL | E_NOTICE | E_STRICT );
ini_set( 'display_errors', 'on' );
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Command\Command;
use Goutte\Client;
use \DomainFinder\DomainFinder;

$console = new Application('SEO Tools', '1.0');

$console
    ->register('find')
    ->setDefinition(array(
        new InputArgument( 'domain', null, InputArgument::REQUIRED, 'Domain to find'),
        new InputArgument( 'query', null, InputArgument::REQUIRED, 'Keywords to search'),
    ))
    ->setDescription('Find the position of your domain in google search results')
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($console){
    	$time 	= microtime(true);
    	$domain = $input->getArgument('domain');

		$table 	= $console->getHelperSet()->get( 'table' );
		$table->setHeaders( array( '#', 'Url', 'Is Yours?' ) );

		$event_dispatcher 	= new \DomainFinder\Event\EventDispatcher();
		$event_dispatcher->addSubscriber( new \DomainFinder\Event\OutputListener( $output ) );
		$domain_finder 		= new DomainFinder( $domain, 10, $event_dispatcher );
		$domain_finder->find( $input->getArgument('query') );

		$counter = 0;
		var_dump( $domain_finder->getGoogleResults()->export() );die;
		foreach ( $domain_finder->getGoogleResults() as $result ) {
			$table->addRow( array( ++$counter, $result->getHost(), ( $result->is($domain)?'[X]':'[]' ) ) );
		}

		$table->render( $output );
		$output->writeln( "<info>Elapsed time: " . round( microtime(true) - $time, 3 ) . "</info>");
    })
;
$console->setCatchExceptions(false);
$console->run();
